En Julia contamos con una colección de datos llamada tupla, la cuál puede contener todo tipo de valor pero es inmutable, una vez creada no se puede modificar.
Se puede trabajar con ellas a tráves de sus indices.

In [1]:
(23,'a',3.2,"Hola")

(23, 'a', 3.2, "Hola")

In [11]:
∅=0,'a'

(0, 'a')

In [53]:
s = ('h','o','l','a')

('h', 'o', 'l', 'a')

In [54]:
s[3]

'l': ASCII/Unicode U+006C (category Ll: Letter, lowercase)

Se pueden hacer operaciones con ellas (tipos numericos)

In [21]:
(2,5,6).+(5,7,2)

(7, 12, 8)

In [25]:
(2,5,6).*(5,7,2)

(10, 35, 12)

Hay algo llamdo tuples con nombres, esto quiere decir que a cada elemento de la tupla le asignamos un identificador, algo así como el nombre del índice

In [26]:
t = (saludo = "Hola", nombre = "Rafael")

(saludo = "Hola", nombre = "Rafael")

In [27]:
t.saludo

"Hola"

In [28]:
t.nombre

"Rafael"

In [29]:
t[1]

"Hola"

In [33]:
t.saludo * " " * t.nombre

"Hola Rafael"

In [35]:
(1:20...,)

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20)

In [45]:
abc = ('a':'z'...,)

('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z')

Los dos anteriores ejemplos nos construyen una lista con elementos entre 1 y 20 para el primero y en el segundo entre el valor ascii de 'a' y el valor ascii de 'b'.

Para el segundo caso si lo ponemos con comillas dobles nos marcara error, esto debido a que con las comillas dobles es una cadena

En el caso de las matrices, es similar a las tuplas solo que ahora usaremos corchetes en lugar de paréntesis

In [55]:
[1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [56]:
[ 1 2 3;4 5 6;7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

Se utilizan el ; para separar cada renglón

In [60]:
zeros(2,2)

2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0

zeros crea una matriz de ceros con las filas y columnas que le indiquemos, sino indicamos el tipo de dato, la creara de tipo flotante de 64bits

In [61]:
zeros(Int,3,3)

3×3 Matrix{Int64}:
 0  0  0
 0  0  0
 0  0  0

In [62]:
ones(2,3)

2×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0

Existen otras variaciones como trues y falses, que podrían ser parecidas a ones y zeros, pero aquí en realidad son los tipos booleanos, verdadero y falso

In [77]:
trues(2,2)

2×2 BitMatrix:
 1  1
 1  1

In [78]:
falses(2,2)

2×2 BitMatrix:
 0  0
 0  0

Otra función interesante es rand, la cuál nos permite crear una matriz con números aleatorios

In [94]:
rand(2,4)

2×4 Matrix{Float64}:
 0.802548  0.362679   0.0643667  0.362226
 0.208075  0.0196953  0.589822   0.968881

In [95]:
rand(Int,3,4)

3×4 Matrix{Int64}:
   191428336582576609  -7337758105798758488  …  -6506477882503984034
  7868456937947634255   4015315719533467518     -1143668177028897722
 -8089313235818217607  -7759068056241484315      6251038846851299777

In [98]:
rand(Bool,2,3)

2×3 Matrix{Bool}:
 0  0  1
 1  0  0

In [99]:
rand(Char, 2,4,2)

2×4×2 Array{Char, 3}:
[:, :, 1] =
 '\U73265'  '\U7d8a1'  '\U6477b'  '\U3fc61'
 '\U93a2e'  '\Ufeccf'  '\U982ef'  '\Ueecaf'

[:, :, 2] =
 '\U797fc'   '\Ub1b4c'  '\U95d83'  '\U54a31'
 '\U103ac3'  '\Ufe8af'  '\Ud6e0a'  '\Ue6bef'

Otra función interesante es fill, la cuál nos llena la matriz con lo que le indiquemos

In [102]:
fill('a',2,2)

2×2 Matrix{Char}:
 'a'  'a'
 'a'  'a'

In [103]:
fill(3,2,2)

2×2 Matrix{Int64}:
 3  3
 3  3

In [104]:
fill(true,2,2)

2×2 Matrix{Bool}:
 1  1
 1  1

In [105]:
fill(2+3im,2,2)

2×2 Matrix{Complex{Int64}}:
 2+3im  2+3im
 2+3im  2+3im

In [106]:
fill(2//3,2,2)

2×2 Matrix{Rational{Int64}}:
 2//3  2//3
 2//3  2//3

De igual manera es posible acceder a los elementos de una matriz a tráves de sus indice, en el caso de tener más de una fila o columna, habrá que indicar ambos

In [107]:
m = rand(3,3)

3×3 Matrix{Float64}:
 0.85038   0.542737  0.93576
 0.306083  0.245391  0.594729
 0.657365  0.686769  0.981714

In [110]:
m[2, 1]

0.30608349152912906

También podemos hacer uso de ':' para indicar el rango de elementos

In [111]:
m = rand(4,4)

4×4 Matrix{Float64}:
 0.208119  0.756435  0.187255   0.664564
 0.990136  0.261436  0.0820242  0.930279
 0.155537  0.492313  0.439449   0.191993
 0.473218  0.299037  0.451644   0.325869

In [113]:
m[1:2,3:4]

2×2 Matrix{Float64}:
 0.187255   0.664564
 0.0820242  0.930279

In [114]:
m[:,3:4]

4×2 Matrix{Float64}:
 0.187255   0.664564
 0.0820242  0.930279
 0.439449   0.191993
 0.451644   0.325869

A diferencia de las tuplas en las matrices si podemos modificar sus valores, ya sea la matriz completa o alguno de sus elementos a tráves de sus índices

In [117]:
m[2,1] = 3

3

In [118]:
m

4×4 Matrix{Float64}:
 0.208119  0.756435  0.187255   0.664564
 3.0       0.261436  0.0820242  0.930279
 0.155537  0.492313  0.439449   0.191993
 0.473218  0.299037  0.451644   0.325869

In [120]:
m[2:3,3:4] = ones(2,2)

2×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0

In [121]:
m

4×4 Matrix{Float64}:
 0.208119  0.756435  0.187255  0.664564
 3.0       0.261436  1.0       1.0
 0.155537  0.492313  1.0       1.0
 0.473218  0.299037  0.451644  0.325869

In [126]:
for n in m
    println(n)
end

0.20811936707476741
3.0
0.1555368075301906
0.47321811265790803
0.7564350593018545
0.2614361589781524
0.4923129255332761
0.2990369280776295
0.1872548529607876
1.0
1.0
0.4516439579365059
0.6645641083874019
1.0
1.0
0.3258693843391536


Otra manera es la función eachindex, la cuál nos sirve para obtener el indice mientras iteramos

In [128]:
saludos = ["Hola" "¿Qué tal?" "Saludos"]

1×3 Matrix{String}:
 "Hola"  "¿Qué tal?"  "Saludos"

In [134]:
for p in eachindex(saludos)
    println(p,". $(saludos[p])")
end

1. Hola
2. ¿Qué tal?
3. Saludos


Una función también muy útil es la función push, la cuál nos permite añadir un elemento al final de un vector(matriz de una fila o columna)

In [150]:
arr = [1:10...,]

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [151]:
push!(arr,11,12)

12-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12

In [152]:
push!(arr,13,14)

14-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14

Contrario a push, existe pop, la cuál nos permite eliminar el último elemento de un vector

In [153]:
pop!(arr)

14

In [155]:
arr

13-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13

In [156]:
pop!(arr)

13

In [157]:
pop!(arr)

12

In [159]:
pop!(arr)

10

In [160]:
arr

9-element Vector{Int64}:
 1
 2
 3
 4
 5
 6
 7
 8
 9

Otra función que puede ser útil es la de copy, la cuál nos permite copiar un vector o una matriz en otro

In [164]:
arr2 = copy(arr)

9-element Vector{Int64}:
 1
 2
 3
 4
 5
 6
 7
 8
 9

Otra forma de crear arrays es mediante comprensiones, la cuál en vez de usar ciclos, hacemos todo desde la definición de la matriz

In [175]:
[x += 1 for x = 1:10 if x/2 > 3]

4-element Vector{Int64}:
  8
  9
 10
 11

In [173]:
x = []
for i in 1:10
    if i/2 > 3
        push!(x,i+1)
    end
end

In [174]:
x

4-element Vector{Any}:
  8
  9
 10
 11

Al utilizar comprensiones optimizamos código y rendimiento.

No solo a vectores también se puede con matrices

In [177]:
[x += y for x = 1:5, y = 11:15]

5×5 Matrix{Int64}:
 12  13  14  15  16
 13  14  15  16  17
 14  15  16  17  18
 15  16  17  18  19
 16  17  18  19  20